services:
  database:
    image: postgres:latest
    restart: always
    container_name: notes-app-backend-container
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    container_name: adminer-container
    ports:
      - 8080:8080